1. Write a Python Program to Add Two Matrices?

In [2]:
A = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

B = [[5,8,1],
    [6,7,3],
    [4,5,9]]

res = [[A[i][j] + B[i][j]  for j in range(len(A[0]))] for i in range(len(A))]

for r in res:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


2. Write a Python Program to Multiply Two Matrices?


In [3]:
import numpy as np

X = [[2, 7, 3],
    [4, 4, 6],
    [7, 3, 9]]
 

Y = [[8, 8, 1, 2],
    [3, 7, 3, 0],
    [5, 5, 9, 1]]
 
# result will be 3x4
 
res= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]
 
res = np.dot(X,Y)
 
for r in res:
    print(r)

[52 80 50  7]
[74 90 70 14]
[110 122  97  23]



3. Write a Python Program to Transpose a Matrix?


In [4]:
import numpy as np

arr = np.array([[4, 5, 6], [4, 5, 6]])

print(f'Original Array:\n{arr}')

arr_transpose = arr.transpose()

print(f'Transposed Array:\n{arr_transpose}')

Original Array:
[[4 5 6]
 [4 5 6]]
Transposed Array:
[[4 4]
 [5 5]
 [6 6]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
def sortWords():
    str =input('Enter a word:').title()
    print(str) 
    sorted_list =sorted(str.split(' '))
    print(' '.join(sorted_list))

sortWords()

There Are Many States In Inida
Are In Inida Many States There


5. Write a Python Program to Remove Punctuation From a String?

In [12]:
def remPunctuations():
    punctuations ='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_put =input('Enter a string: ')
    print(in_put)
    out_put =''
    for i in in_put:
        if i not in punctuations:
            out_put +=i 
    print(out_put) 
remPunctuations()           

I am @#$%&@)  #@^&  a life $^&(&^^ long %^&* student.
I am     a life  long  student
